# Generated by Django 2.2.7 on 2020-01-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_booksreviewcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksreviewcomment',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.BooksReview'),
            preserve_default=False,
        ),
    ]
