# Generated by Django 2.2.7 on 2020-01-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20191209_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialsReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('tutorials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tutorials.TutorialsReview')),
            ],
        ),
    ]
